### ISSUE TITLE
Can we use this as a templat to make typescript packages?

### ISSUE THREAD

**Issue by fayazara** [unjs/template#102]
### Describe the change

Hey @pi0, planning to use this template for some TypeScript packages I'm building. Can we? The docs don't clarify its purpose. 

### Additional information

- [X] Would you be willing to help?

**Comment by pi0** [comment]
Generally yes this is template i used for creating many of new unjs packages which made with typescript.

**Comment by fayazara** [comment]
Okay, the CI keeps failing with this message - 

```
Run pnpm install
 ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE  Cannot perform a frozen installation because the version of the lockfile is incompatible with this version of pnpm
 ```
 
 Any idea?

**Comment by pi0** [comment]
`pnpm install`

**Comment by fayazara** [comment]
I meant the the pipeline fails immidiately, even for new repos 

https://github.com/SupersaasHQ/usePayment/actions/runs/11477581779/job/31939974451
https://github.com/SupersaasHQ/usePayment/actions/runs/11477581785/job/31939974510

**Comment by pi0** [comment]
After cloning template, you are supposed to run `pnpm install` once (similar to Nuxt starter templates). If you clone with giget, it has `--install` option

**Comment by fayazara** [comment]
Thanks @pi0
