### ISSUE TITLE
`standard-version` package has been deprecated

### ISSUE THREAD

**Issue by NozomuIkuta** [unjs/template#22]
I found that, as of 15th May 2022, the maintainer had announced that he would no longer maintain `standard-version` package (https://github.com/conventional-changelog/standard-version/pull/907).

So, it would be better to consider to use an alternative or create one. 🤔 

- The maintainer recommends to use [Google's release-please](https://github.com/googleapis/release-please) package
- @TimothyJones' folked version: [commit-and-tag-version](https://github.com/absolute-version/commit-and-tag-version) package
- etc.

---

By the way, if I'm correct, `standard-version@v9.5.0` seems to have at least one bug that it doesn't bump up version correctly. For example, it bumps up the patch version only even if I added a feature (see the diff below).

https://github.com/NozomuIkuta/h3-cors/commit/8265c7a3a7ff4d784ad77b653d4f127e336d8ed9

**Comment by TimothyJones** [comment]
Just chiming in to say that actually isn’t a bug- it’s because the semver behaviour below 1.0.0 is defined by convention instead of specification. You can see some discussion in this comment: https://github.com/absolute-version/commit-and-tag-version/issues/26#issuecomment-1155303502

**Comment by pi0** [comment]
Thanks for creating issue!

Working on [unjs/changelogen](https://github.com/unjs/changelogen) with release support (`changeloggen --release`) which does same steps of `standard-version`. Also respects 0.x semver bumps.

**Comment by NozomuIkuta** [comment]
@TimothyJones 

> that actually isn’t a bug- it’s because the semver behaviour below 1.0.0 is defined by convention instead of specification.

Thank you for pointing it out!
I didn't know such behavior. 😳 

@pi0 

I see 🙋‍♂️ 
Then, I will check the repo and look for something that I can help!

**Comment by pi0** [comment]
Moved to changelogen
